# Generated by Django 3.0.8 on 2020-07-25 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tauschboerse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gegenstand',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
