# Generated by Django 3.0.8 on 2020-07-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauschboerse', '0003_auto_20200725_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gegenstand',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
