# Generated by Django 3.0.8 on 2020-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauschboerse', '0004_auto_20200725_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gegenstand',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
