# Generated by Django 3.0.8 on 2020-08-25 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tauschboerse', '0005_auto_20200803_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gegenstand',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
